### ISSUE TITLE
断开的连接不会清理

### ISSUE THREAD

**Issue by fly0wing** [gearcode/brush#2]
断开的连接，仍然在待连接列表中。

**Comment by gearcode** [comment]
在ubuntu上重现了此BUG：
Client端连接上服务后，直接结束进程，端口从“ESTABLISHED”状态进入“TIME_WAIT”状态，系统并未释放此端口及TCP连接，但Server端通过netstat命令查看相关端口已不存在。
1.Client端需优雅退出netty；
2.Server端的心跳机制，可能并未检测到异常，没有起到清理链接的作用；

**Comment by gearcode** [comment]
已解决
